import logging
from datetime import datetime, timezone
from typing import List, Optional, Tuple

from anthropic import Anthropic

from app.config import settings

logger = logging.getLogger(__name__)

_client: Optional[Anthropic] = None

ANSWER_INSTRUCTIONS = (
    "Answer in English, short, natural, and speakable, as if a voice "
    "assistant (Siri) were going to read it out loud. Don't use markdown, "
    "lists, or formatting: plain text only, one or two sentences. If the "
    "memories don't contain enough information to answer, say so briefly "
    "and directly."
)

RECORD_MEMORY_TOOL = {
    "name": "record_memory_summary",
    "description": (
        "Records a short summary of a personal memory the user dictated, "
        "and, if the text refers to a specific future date and time, a "
        "reminder timestamp."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "summary": {
                "type": "string",
                "description": (
                    "A short, clear, one-sentence summary of the memory, "
                    "preserving names, dates, and concrete details. Don't "
                    "invent information that isn't in the original text."
                ),
            },
            "reminder_at": {
                "type": ["string", "null"],
                "description": (
                    "If the text mentions a specific future date/time (e.g. "
                    "'Thursday at 3pm', 'tomorrow morning', 'in two hours'), "
                    "the resolved timestamp as ISO 8601 with a UTC offset "
                    "(e.g. '2026-07-30T15:00:00-06:00'). Null if no specific "
                    "date/time is mentioned."
                ),
            },
        },
        "required": ["summary"],
    },
}


def _get_client() -> Anthropic:
    global _client
    if _client is None:
        if not settings.anthropic_api_key:
            raise RuntimeError(
                "ANTHROPIC_API_KEY must be set in the environment (.env)"
            )
        _client = Anthropic(api_key=settings.anthropic_api_key)
    return _client


def summarize_memory(text: str) -> Tuple[str, Optional[str]]:
    """Summarizes a memory and, if it mentions one, extracts a reminder time.

    Uses tool use (rather than parsing free-form text) so the date/time
    extraction is structured and doesn't depend on Claude's prose matching
    an expected shape.
    """
    logger.info("Calling Claude to summarize a memory (%d chars)", len(text))
    now = datetime.now(timezone.utc).isoformat()
    system_prompt = (
        "You extract structured data from a short personal memory a user "
        "dictated to a voice assistant. Call record_memory_summary with the "
        f"summary and, if relevant, a reminder_at timestamp. The current "
        f"UTC time is {now}; resolve relative dates/times against it."
    )
    try:
        message = _get_client().messages.create(
            model=settings.claude_model,
            max_tokens=300,
            system=system_prompt,
            tools=[RECORD_MEMORY_TOOL],
            tool_choice={"type": "tool", "name": "record_memory_summary"},
            messages=[{"role": "user", "content": text}],
        )
        tool_use = next(
            block for block in message.content if block.type == "tool_use"
        )
        summary = str(tool_use.input["summary"]).strip()
        reminder_at = tool_use.input.get("reminder_at") or None
        logger.info(
            "Summary generated by Claude (reminder_at=%s)", reminder_at
        )
        return summary, reminder_at
    except Exception:
        logger.exception("Failed calling Claude to summarize the memory")
        raise


def _build_answer_instructions(
    tone: Optional[str],
    voice_style: Optional[str],
    full_name: Optional[str],
    pronouns: Optional[str],
) -> str:
    instructions = ANSWER_INSTRUCTIONS
    style_bits = []
    if tone:
        style_bits.append(f"tone: {tone}")
    if voice_style:
        style_bits.append(f"personality: {voice_style}")
    if style_bits:
        instructions += (
            " Match the user's preferred speaking style (" + ", ".join(style_bits) + ")."
        )
    if full_name:
        instructions += (
            f" The user's name is {full_name} — use it naturally once in a while (e.g. "
            "at the start of an answer), not in every sentence."
        )
    if pronouns:
        instructions += f" If you refer to the user in the third person, their pronouns are {pronouns}."
    return instructions


def generate_answer(
    question: str,
    context_memories: List[str],
    tone: Optional[str] = None,
    voice_style: Optional[str] = None,
    full_name: Optional[str] = None,
    pronouns: Optional[str] = None,
) -> str:
    logger.info(
        "Calling Claude to answer the question using %d context memories",
        len(context_memories),
    )
    context_block = (
        "\n".join(f"- {memory}" for memory in context_memories)
        if context_memories
        else "(no relevant memories found)"
    )
    prompt = (
        f"User's saved memories:\n{context_block}\n\n"
        f"User's question: {question}\n\n"
        f"{_build_answer_instructions(tone, voice_style, full_name, pronouns)}"
    )
    try:
        message = _get_client().messages.create(
            model=settings.claude_model,
            max_tokens=200,
            messages=[{"role": "user", "content": prompt}],
        )
        answer = message.content[0].text.strip()
        logger.info("Answer generated successfully by Claude")
        return answer
    except Exception:
        logger.exception("Failed calling Claude to generate the answer")
        raise
